server.port=8080

# API key for Google Gemini AI
gemini.api.key=${GOOGLE_GENERATIVE_AI_API_KEY:}

# Firebase configuration parameters
firebase.project.id=${FIREBASE_PROJECT_ID:}
firebase.client.email=${FIREBASE_CLIENT_EMAIL:}
firebase.private.key=${FIREBASE_PRIVATE_KEY:}
